---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Build mon_image_mysql
      docker_image:
        path: ./docker/mysql
        name: mon_image_mysql
        source: build

    - name: Build mon_image_python
      docker_image:
        path: ./docker/python
        name: mon_image_python
        source: build

    - name: Build mon_image_nginx
      docker_image:
        path: ./docker/nginx
        name: mon_image_nginx
        source: build

    - name: Build mon_image_newman
      docker_image:
        path: ./docker/newman
        name: mon_image_newman
        source: build

    - name: Create network intNetwork
      docker_network:
        name: intNetwork
        ipam_options:
          subnet: '172.10.0.0/16'

    - name: Run mon_image_mysql container
      docker_container:
        name: mysql
        image: mon_image_mysql
        state: started
        ip: 172.10.0.10
        ports:
          - "3306:3306"
        networks:
          - name: intNetwork

    - name: Run mon_image_python container
      docker_container:
        name: python
        image: mon_image_python
        state: started
        ip: 172.10.0.20
        ports:
          - "8000:8080"
        networks:
          - name: intNetwork

    - name: Run mon_image_nginx container
      docker_container:
        name: nginx
        image: mon_image_nginx
        state: started
        ip: 172.10.0.30
        ports:
          - "80:80"
        networks:
          - name: intNetwork

    - name: Run mon_image_newman container
      docker_container:
        name: newman
        image: mon_image_newman
        state: started
        ip: 172.10.0.40
        networks:
          - name: intNetwork
