version: '2.4'
services:

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
  api:
    build:
      context: ./python
      dockerfile: Dockerfile
    depends_on:
    - db
    ports:
      - 80:80
